services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: J8H7g8h
      POSTGRES_DB: ep
      PGPORT: 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: bash -c "rm -rf /var/lib/postgresql/data/* && docker-entrypoint.sh postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  EPTriviaBot:
    build:
      context: .
    container_name: EPTriviaBot
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres_db
    command: sh -c "npm run dev"

volumes:
  postgres_data: