version: "3.8"

services:
  mariadb_db:
    image: mariadb:latest
    container_name: mariadb_db
    env_file:
      - ./app/.env
    ports:
      - "5434:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "-p$MARIADB_ROOT_PASSWORD",
        ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - app_network

  ep_trivia_bot:
    container_name: EPTriviaBot
    build:
      context: .
      dockerfile: ./.docker/Node/Dockerfile
    depends_on:
      - mariadb_db
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
