version: '3.8'

services:
  mariadb_db:
    image: mariadb:latest
    container_name: mariadb_db
    env_file:
      - ./app/.env
    ports:
      - "5434:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  ep_trivia_bot:
    container_name: EPTriviaBot
    build:
      context: .
      dockerfile: ./.docker/Node/Dockerfile
    depends_on:
      - mariadb_db
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
      
volumes:
  mariadb_data:
