version: '3.8'

services:
  mariadb_db:
    image: mariadb:latest
    container_name: mariadb_db
    ports:
      - "5434:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  ep_trivia_bot:
    build:
      dockerfile: ./.docker/Node/Dockerfile
      context: .
    container_name: EPTriviaBot
    depends_on:
      - mariadb_db
    env_file:
      - .env
    command: sh -c "npm run dev"

volumes:
  mariadb_data:
