services:
  maria_db:
    container_name: maria_db
    build:
      context: .
      dockerfile: .docker/Mariadb/Dockerfile
    env_file:
      - ./app/.env
    ports:
      - "5434:3306"
    volumes:
      - maria_db_data:/var/lib/mysql
    networks:
      - app_network

  php_my_admin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    env_file:
      - ./app/.env
    ports:
      - "8080:80"
    depends_on:
      - maria_db
    networks:
      - app_network

  trivia_bot:
    container_name: TriviaBot
    build:
      context: .
      dockerfile: .docker/Node/Dockerfile
    depends_on:
      - maria_db
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  maria_db_data:
